import { images } from "@/constants";

export const carsInfo = [
  {
    id: '1',
    name: 'BMW Cabrio',
    model: 'Cabriolet 430i',
    capacity: 3,
    color: 'Red',
    fuelType: 'Octane',
    gearType: 'Automatic',
    distance: '800m (5mins away)',
    rating: 4.9,
    reviews: 531,
    maxPower: '255 hp',
    zeroToSixty: '5.9s',
    tankSize: '59 L',
    maxSpeed: '250 km/h',
    image: images.bmw,
  },
  {
    id: '2',
    name: 'Tesla Model 3',
    model: 'Model 3 Long Range',
    capacity: 5,
    color: 'White',
    fuelType: 'Electric',
    gearType: 'Automatic',
    distance: '1.2km (7mins away)',
    rating: 4.8,
    reviews: 872,
    maxPower: '450 hp',
    zeroToSixty: '4.2s',
    tankSize: '82 kWh',
    maxSpeed: '233 km/h',
    image: images.audi,
  },
  {
    id: '3',
    name: 'Toyota Corolla',
    model: '2022 LE',
    capacity: 5,
    color: 'Blue',
    fuelType: 'Petrol',
    gearType: 'Manual',
    distance: '500m (3mins away)',
    rating: 4.6,
    reviews: 431,
    maxPower: '139 hp',
    zeroToSixty: '8.2s',
    tankSize: '50 L',
    maxSpeed: '180 km/h',
    image: images.jaguar,
  },
  {
    id: '4',
    name: 'Mercedes A-Class',
    model: 'A220 4MATIC',
    capacity: 4,
    color: 'Silver',
    fuelType: 'Diesel',
    gearType: 'Automatic',
    distance: '2km (10mins away)',
    rating: 4.7,
    reviews: 652,
    maxPower: '188 hp',
    zeroToSixty: '7.1s',
    tankSize: '51 L',
    maxSpeed: '210 km/h',
    image: images.audi,
  },
  {
    id: '5',
    name: 'Ford Mustang',
    model: 'GT Fastback',
    capacity: 4,
    color: 'Black',
    fuelType: 'Octane',
    gearType: 'Manual',
    distance: '1km (6mins away)',
    rating: 4.5,
    reviews: 388,
    maxPower: '450 hp',
    zeroToSixty: '4.3s',
    tankSize: '61 L',
    maxSpeed: '250 km/h',
    image: images.mustang,
  },
  {
    id: '6',
    name: 'Audi Q5',
    model: 'Premium Plus 45 TFSI',
    capacity: 5,
    color: 'Gray',
    fuelType: 'Diesel',
    gearType: 'Automatic',
    distance: '1.8km (8mins away)',
    rating: 4.6,
    reviews: 493,
    maxPower: '261 hp',
    zeroToSixty: '5.7s',
    tankSize: '70 L',
    maxSpeed: '240 km/h',
    image: images.audi,
  },
  {
    id: '7',
    name: 'Kia Sportage',
    model: 'SX Prestige',
    capacity: 5,
    color: 'Green',
    fuelType: 'Petrol',
    gearType: 'Automatic',
    distance: '950m (5mins away)',
    rating: 4.4,
    reviews: 215,
    maxPower: '187 hp',
    zeroToSixty: '8.3s',
    tankSize: '54 L',
    maxSpeed: '201 km/h',
    image: images.audi,
  },
  {
    id: '8',
    name: 'Honda Civic',
    model: 'Sport Touring',
    capacity: 5,
    color: 'Blue',
    fuelType: 'Petrol',
    gearType: 'Manual',
    distance: '600m (4mins away)',
    rating: 4.3,
    reviews: 342,
    maxPower: '180 hp',
    zeroToSixty: '7.4s',
    tankSize: '47 L',
    maxSpeed: '200 km/h',
    image: images.audi,
  },
  {
    id: '9',
    name: 'Volkswagen Golf',
    model: 'GTI Performance',
    capacity: 5,
    color: 'Red',
    fuelType: 'Hybrid',
    gearType: 'Automatic',
    distance: '1.1km (6mins away)',
    rating: 4.5,
    reviews: 289,
    maxPower: '241 hp',
    zeroToSixty: '6.2s',
    tankSize: '50 L',
    maxSpeed: '210 km/h',
    image: images.audi,
  },
  {
    id: '10',
    name: 'Chevrolet Camaro',
    model: 'LT1 Coupe',
    capacity: 4,
    color: 'Yellow',
    fuelType: 'Octane',
    gearType: 'Manual',
    distance: '1.5km (9mins away)',
    rating: 4.2,
    reviews: 174,
    maxPower: '455 hp',
    zeroToSixty: '4.0s',
    tankSize: '72 L',
    maxSpeed: '250 km/h',
    image: images.audi,
  },
  {
    id: '11',
    name: 'Nissan Leaf',
    model: 'SV Plus',
    capacity: 5,
    color: 'White',
    fuelType: 'Electric',
    gearType: 'Automatic',
    distance: '700m (4mins away)',
    rating: 4.7,
    reviews: 505,
    maxPower: '214 hp',
    zeroToSixty: '6.9s',
    tankSize: '62 kWh',
    maxSpeed: '144 km/h',
    image: images.audi,
  },
];
