export const notifications = [
  {
    id: 1,
    type: 'Payment confirm',
    text: 'Lorem ipsum dolor sit amet consectetur. Ultrici es tincidunt eleifend vitae Lorem ipsum dolor sit amet consectetur. Ultrici es tincidunt eleifend vitae',
    time: '15 min ago',
    bg: true,
  },
  {
    id: 2,
    type: 'Payment confirm',
    text: 'Lorem ipsum dolor sit amet consectetur. Ultrici es tincidunt eleifend vitae Lorem ipsum dolor sit amet consectetur. Ultrici es tincidunt eleifend vitae',
    time: '15 min ago',
    bg: false,
  },
  {
    id: 3,
    type: 'Payment confirm',
    text: 'Lorem ipsum dolor sit amet consectetur. Ultrici es tincidunt eleifend vitae Lorem ipsum dolor sit amet consectetur. Ultrici es tincidunt eleifend vitae',
    time: '15 min ago',
    bg: true,
  },
  {
    id: 4,
    type: 'Ride reminder',
    text: 'Your scheduled ride is approaching. Please be ready at your pickup location 10 minutes before time.',
    time: '30 min ago',
    bg: false,
  },
  {
    id: 5,
    type: 'Promotion',
    text: 'Get 15% off your next ride! Offer valid until the end of the week.',
    time: '1 hour ago',
    bg: true,
  },
  {
    id: 6,
    type: 'Trip summary',
    text: 'Your recent trip from Victoria Island to Lekki Phase 1 has been completed successfully.',
    time: '2 hours ago',
    bg: false,
  },
  {
    id: 7,
    type: 'Account update',
    text: 'Your payment method was updated successfully. No action is required.',
    time: '3 hours ago',
    bg: true,
  },
  {
    id: 8,
    type: 'New feature',
    text: 'Introducing in-app chat! You can now message your driver directly.',
    time: '6 hours ago',
    bg: false,
  },
  {
    id: 9,
    type: 'Security alert',
    text: 'New login detected on your account. If this wasn’t you, please reset your password immediately.',
    time: '8 hours ago',
    bg: true,
  },
  {
    id: 10,
    type: 'Service feedback',
    text: 'We value your opinion. Please take a moment to rate your recent ride experience.',
    time: '12 hours ago',
    bg: false,
  },
  {
    id: 11,
    type: 'Payment failed',
    text: 'Your recent payment could not be processed. Please update your billing information.',
    time: '1 day ago',
    bg: true,
  },
  {
    id: 12,
    type: 'Driver assigned',
    text: 'Your driver James is on the way and should arrive in 5 minutes.',
    time: '1 day ago',
    bg: false,
  },
  {
    id: 13,
    type: 'Referral bonus',
    text: 'You earned ₦500 bonus for referring a friend. It’s been added to your wallet.',
    time: '2 days ago',
    bg: true,
  },
  {
    id: 14,
    type: 'Scheduled ride',
    text: 'Reminder: You have a ride scheduled tomorrow at 8:00 AM.',
    time: '2 days ago',
    bg: false,
  },
  {
    id: 15,
    type: 'Document verification',
    text: 'Your driver’s license has been verified successfully.',
    time: '3 days ago',
    bg: true,
  },
  {
    id: 16,
    type: 'Reward unlocked',
    text: 'Congratulations! You unlocked a free ride after 10 trips.',
    time: '3 days ago',
    bg: false,
  },
  {
    id: 17,
    type: 'App update',
    text: 'A new version of the app is available. Please update to enjoy the latest features.',
    time: '4 days ago',
    bg: true,
  },
  {
    id: 18,
    type: 'Location change',
    text: 'Your pickup location was updated to your current GPS location.',
    time: '5 days ago',
    bg: false,
  },
  {
    id: 19,
    type: 'Support reply',
    text: 'Your support request has been answered. Check your inbox for details.',
    time: '5 days ago',
    bg: true,
  },
  {
    id: 20,
    type: 'Weekly summary',
    text: 'You completed 6 trips this week. Keep riding to earn more rewards!',
    time: '6 days ago',
    bg: false,
  },
];
